config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'
  get 'tags/:tag', to: 'movies#index', as: :tag

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :movies, only: [:index, :create, :edit, :update]

  namespace :api do
    namespace :v1 do
      resources :movies, only: [:update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  validates_presence_of :title
  has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by!(name: name).movies
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :movies, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates_confirmation_of :password
  has_secure_password
  has_many :movies
end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < ApplicationController
  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      render json: @movie
    else
      render json: @movie.erros.full_messages, status: 500
    end
  end

  private

  def movie_params
    params.permit(:watched)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if current_user != nil
      @movies = if params[:tag]
        Movie.tagged_with(params[:tag])
      else
        @movies = current_user.movies.all
      end
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    movie = Movie.find(params[:id].to_i)
    if movie.update(movie_params)
      flash[:success] = "Update Successful!"
      redirect_to root_path
    else
      error = movie.errors.messages.first[1][0]
      flash[:error] = possible_errors[error]
      redirect_to edit_movie_path(movie)
    end
  end

  def create
    movie = current_user.movies.create(movie_params)
    if movie.save
      flash[:success] = "Movie successfully created!"
      redirect_to root_path
    else
      error = movie.errors.messages.first[1][0]
      flash[:notice] = possible_errors[error]
      redirect_to root_path
    end
  end

  private

  def movie_params
    params.permit(:title, :note, :tag_list)
  end

  def possible_errors
    {"can't be blank" => "There must be a title!"}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
      redirect_to :root
    else
      flash[:warning] = "Oops, something went wrong! Try logging in or signing up!"
      redirect_to :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to :root
    else
      error = user.errors.messages.first[1][0]
      flash[:error] = possible_errors[error]
      redirect_to :signup
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def possible_errors
    {"has already been taken" => "Another user already has this email!",
     "doesn't match Password" => "Your passwords do not match!"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod4FinalRetake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<%= flash[:error] %>
<h2> Edit your movie! </h2>

<%= form_tag "/movies/#{@movie.id}", method: 'put' do %>
    Title: <%= text_field_tag :title, @movie.title %>
    Note: <%= text_field_tag :note, @movie.note %>
    Tags: <%= text_field_tag :tag_list %>
    <%= submit_tag 'Update Movie' %>
<% end %>

app/views/movies/index.html.erb
<% if current_user %>
  Welcome <%= current_user.email %><br>
  <%= link_to "Logout", logout_path, method: "delete" %>

<%= flash[:success] %>
<%= flash[:notice] %>

<h2>Create a movie here!!</h2>
  <%= form_tag movies_path do %>
    <%= label_tag :title %>
    <%= text_field_tag :title %>

    <%= label_tag :note %>
    <%= text_field_tag :note %>

    <%= submit_tag "Create Movie"%>
  <% end %>

  <div>
    Filter by title: <input id="filter-input">
    <button id='filter-by-watched'>Show only my Watched</button>
    <button id='filter-by-unwatched'>Show only my UNwatched</button>
    <button id='sort-alpha'>Sort Alphabetically by Title</button>
  </div>

  <table>
  <tr>
    <th>Movie Title</th>
    <th>Notes</th>
    <th>Seen?</th>
    <th>Tags</th>
    <th>Watched?</th>
    <th>Edit</th>
  </tr>
    <tbody id="movie-table-body">
    <% @movies.each do |movie| %>
      <% if movie.watched == false %>
        <tr id= <%= movie.id %>>
          <td class="movie-title"><%= movie.title %></td>
          <td class="movie-note"><%= movie.note %></td>
          <td class="status"><%= movie.watched %></td>
          <td class="tags"><%= raw movie.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
          <td><button type="button" name="mark-as-watched" class="mark-watched">Mark as Watched</button></td>
          <td><%= link_to "Edit Movie", edit_movie_path(movie.id) %></td>
        </tr>
        <% else %>
        <tr class="grey" id= <%= movie.id %>>
          <td class="movie-title"><%= movie.title %></td>
          <td class="movie-note"><%= movie.note %></td>
          <td class="status"><%= movie.watched %></td>
          <td class="tags"><%= raw movie.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
          <td><button type="button" name="mark-as-unwatched" class="mark-unwatched">Mark as Unwatched</button></td>
          <td><%= link_to "Edit Movie", edit_movie_path(movie.id) %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

<% else %>
  <h2><%= link_to "Sign Up", signup_path %> or <%= link_to "Login", login_path %></h2>
<% end %>

app/views/users/new.html.erb
<%= flash[:error] %>
<h2>Sign up here!</h2>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>